// <auto-generated />
using System;
using CRMS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230615075532_backend")]
    partial class backend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMS.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CRMS.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDetailId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("BookingDetailId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CarId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("CRMS.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Automatic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Automatic = "Automatic",
                            Brand = "Tesla",
                            CarName = "Tesla Malibu",
                            Description = "The Tesla Model 3 is an electric car produced by American automaker Tesla. It is a battery-powered four-door sedan that is marketed in the compact-executive segment.",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://i.pinimg.com/originals/de/a7/88/dea7880f7dd2140295584422cc857dea.jpg",
                            Model = "Model 3",
                            PricePerDay = 2000.0,
                            Rating = 112,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 2,
                            Automatic = "Automatic",
                            Brand = "Toyota",
                            CarName = "Toyota Urban Cruiser Hyryder",
                            Description = "The Toyota Urban Cruiser is an automobile nameplate used by the Japanese automobile manufacturer Toyota since 2008 for several subcompact crossover SUV models: Toyota Urban Cruiser Concept, a concept car showcased in 2006",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://tse2.mm.bing.net/th/id/OIP._TjxvsWVUbHHwXdBNbBv2gAAAA?pid=ImgDet&rs=1",
                            Model = "Model-2022",
                            PricePerDay = 2000.0,
                            Rating = 102,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 3,
                            Automatic = "Automatic",
                            Brand = "BMW",
                            CarName = "BMW X3",
                            Description = "The BMW X3 is a compact luxury crossover SUV manufactured by BMW since 2003, based on the BMW 5 Series platform. Now in its third generation, BMW markets the car as a Sports Activity Vehicle, the company's proprietary descriptor for its X-line luxury vehicles.",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://media.autoexpress.co.uk/image/private/s--sOxiKAFg--/v1562244603/autoexpress/2017/06/_dsc6820.jpg",
                            Model = "Model-2022",
                            PricePerDay = 7000.0,
                            Rating = 132,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 4,
                            Automatic = "Automatic",
                            Brand = "Nissan",
                            CarName = "Nissan Mercielago",
                            Description = "The Nissan Magnite is a subcompact crossover SUV manufactured and marketed by Nissan. Unveiled in October 2020, the Magnite is placed below the Kicks in Nissan's global SUV lineup, making it the smallest Nissan crossover SUV worldwide",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pannucarrental.com%2Ffleets%2Fnissan-magnite&psig=AOvVaw061xA6lo2X3qfb0g5vsC_6&ust=1686900860001000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCLiUjtXhxP8CFQAAAAAdAAAAABAD",
                            Model = "Model-2022",
                            PricePerDay = 2000.0,
                            Rating = 102,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 5,
                            Automatic = "Automatic",
                            Brand = "Toyota",
                            CarName = "Toyota Camry",
                            Description = "The Toyota Camry (XV30) is a mid-size car produced by Toyota from June 2001 to January 2006. The XV30 series represented the fifth generation of the Toyota Camry in all markets outside Japan, which followed a different generational lineage. The XV30 range is split into different model codes indicative of the engine.",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngwing.com%2Fen%2Ffree-png-svfxa&psig=AOvVaw2DpbXz0HXcoACj7-Rwo1Et&ust=1686901299868000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCJi2iK7jxP8CFQAAAAAdAAAAABAD",
                            Model = "Model-2022",
                            PricePerDay = 2000.0,
                            Rating = 94,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 6,
                            Automatic = "Automatic",
                            Brand = "Volvo",
                            CarName = "Volvo XC90",
                            Description = "The Volvo XC90 is a mid-size luxury SUV manufactured and marketed by Volvo Cars since 2002 and now in its second generation.\r\n\r\nThe first generation was introduced at the 2002 North American International Auto Show and used the Volvo P2 platform shared with the first generation Volvo S80 and other large Volvo cars.",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngwing.com%2Fen%2Ffree-png-tyrpr&psig=AOvVaw3Ye1sywGAcEzgrk8-nLtAu&ust=1686901524554000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCKDJuY_kxP8CFQAAAAAdAAAAABAE",
                            Model = "Model-2022",
                            PricePerDay = 2000.0,
                            Rating = 119,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 7,
                            Automatic = "Automatic",
                            Brand = "Ford",
                            CarName = "Ford Fiesta",
                            Description = "The Ford Fiesta is a supermini car marketed by Ford since 1976 over seven generations. Over the years, the Fiesta has mainly been developed and manufactured by Ford's European operations, and has been positioned below the Escort",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngwing.com%2Fen%2Ffree-png-peluz&psig=AOvVaw04SBRDcFJkNYF5mF8cQpnw&ust=1686901642104000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCNCN8MfkxP8CFQAAAAAdAAAAABAE",
                            Model = "Model 3",
                            PricePerDay = 2000.0,
                            Rating = 82,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        },
                        new
                        {
                            CarId = 8,
                            Automatic = "Automatic",
                            Brand = "Colorado",
                            CarName = "Rolls Royce Colorado",
                            Description = "Rolls-Royce is the world's leading supplier of marine propulsion equipment. Its products and services range from complete ship design to integrated propulsion, maneuvering, and positioning systems and deck machinery.",
                            Gps = "GPS Navigation",
                            ImgUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngwing.com%2Fen%2Fsearch%3Fq%3Drolls%2Broyce&psig=AOvVaw3NsLqkaVxNleCNWqhCRb2N&ust=1686901874745000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCLCgsLjlxP8CFQAAAAAdAAAAABAD",
                            Model = "Model 3",
                            PricePerDay = 2000.0,
                            Rating = 52,
                            SeatType = "Heated seats",
                            Speed = "20kmpl"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("CRMS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 13,
                            Address = "87A south part New Delhi",
                            ConfirmPassword = "asfsdgv",
                            Email = "mennaPriya@gmail.com",
                            Gender = "Female",
                            Password = "asfsdgv",
                            PhoneNumber = "789542589",
                            RoleId = 2,
                            UserName = "MeenaPriya"
                        },
                        new
                        {
                            UserId = 12,
                            Address = "56B Faossil nagar,chennai",
                            ConfirmPassword = "xbdfbxfhbx",
                            Email = "manjuRam@gmail.com",
                            Gender = "male",
                            Password = "xbdfbxfhbx",
                            PhoneNumber = "789542589",
                            RoleId = 2,
                            UserName = "Manju Ram"
                        },
                        new
                        {
                            UserId = 10,
                            Address = "955C Thanikachalam nagar, Bangalore",
                            ConfirmPassword = "090kjg56",
                            Email = "HemaPrasad.com",
                            Gender = "Female",
                            Password = "090kjg56",
                            PhoneNumber = "789542589",
                            RoleId = 2,
                            UserName = "Hema Prasad"
                        });
                });

            modelBuilder.Entity("CRMS.Models.Booking", b =>
                {
                    b.HasOne("CRMS.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMS.Models.BookingDetail", b =>
                {
                    b.HasOne("CRMS.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMS.Models.Car", "Car")
                        .WithMany("BookingDetails")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CRMS.Models.User", b =>
                {
                    b.HasOne("CRMS.Models.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CRMS.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("CRMS.Models.Car", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("CRMS.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
